### ISSUE TITLE
TODO: Erste Protokoll-Version

### ISSUE THREAD

**Issue by real-yfprojects** [real-yfprojects/chattool#5]
## Beschreibung der Aufgabe
Nach dem wir uns generell überlegt haben, welche was/wie und mit wem kommunizieren, muss nun eine erste Version eines Protokolls erdacht werden. Diese kann dann für das Chat-System implementiert werden.

***After #3***

## Gedanken
Ein text-basiertes Protokoll bietet sich an, da es vom Menschen lesbar und vertrauter, verständlicher als ein bit-basiertes Protokoll ist. Ein Beispiel hierfür ist [HTTP 1](https://github.com/real-yfprojects/chattool/wiki/Protokolle#http-1).

## Anforderungen an das Protokoll
Diese Funktionen bzw. Anforderungen sollte das Protokolle unterstützen bzw. erfüllen:

- [x] Namen dem Server bekannt mitteilen
- [x] Empfangen von Nachrichten
- [x] Senden von Nachrichten
- [x] Austausch über Chatteilnehmer
- [x] Verschiedene Nachrichtentypen / Inhaltstypen
- [x] Versionsabgleich
- [x] Downwards kompatible Versionsabfrage
- [x] Unbekannt Nachrichtentypen
- [x] Unbekannte Befehle
- [x] Ignorieren unbekannter "Sachen"

**Comment by real-yfprojects** [comment]
Ich habe ein [Eintwurf](../blob/7fe6082/plan/basic-protocol.txt) erstellt.
